TestBundle\Entity\Accueil:
    type: entity
    table: null
    repositoryClass: TestBundle\Repository\AccueilRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
    lifecycleCallbacks: {  }
