commercant_index:
    path:     /
    defaults: { _controller: "TestBundle:Commercant:index" }
    methods:  GET

commercant_show:
    path:     /{id}/show
    defaults: { _controller: "TestBundle:Commercant:show" }
    methods:  GET

commercant_new:
    path:     /new
    defaults: { _controller: "TestBundle:Commercant:new" }
    methods:  [GET, POST]

commercant_edit:
    path:     /{id}/edit
    defaults: { _controller: "TestBundle:Commercant:edit" }
    methods:  [GET, POST]

commercant_delete:
    path:     /{id}/delete
    defaults: { _controller: "TestBundle:Commercant:delete" }
    methods:  DELETE
